---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    strategy:
      matrix:
        chart: [alpine-base,ubuntu-base,centos-base]
    uses: GrabAByte/github-devops-workflows/.github/workflows/helmLint.yml@feat/helm
    with:
      chartPath: "charts/${{ matrix.chart }}"
  template:
    strategy:
      matrix:
        chart: [alpine-base,ubuntu-base,centos-base]
    uses: GrabAByte/github-devops-workflows/.github/workflows/helmTemplate.yml@feat/helm
    with:
      chartPath: "charts/${{ matrix.chart }}"
      releaseName: "${{ matrix.chart }}"
      valuesPath: "charts/${{ matrix.chart }}/values.yaml"
