---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  helm_matrix:
    strategy:
      matrix:
        chart: [alpine-base,ubuntu-base,centos-base]
    uses: GrabAByte/github-devops-workflows/.github/workflows/helmLint.yml@feat/helm
    with:
      chartPath: "charts/${{ matrix.chart }}"
